ApkFilePath=.//src//main//resources//ApkFiles//General-Store.apk
mainJSFilePath=C:\\Windows\\System32\\node_modules\\appium\\build\\lib\\main.js
TestEnv=stage
IPAddress=127.0.0.1
PortNumber=4723
DeviceName=Device1
PlatformName=android
testdatafilepath=.//src//main//resources//TestData//TestData.xlsx